FactoryGirl.define do
  factory :sub_reddit do
    trait :programming do
      name 'Programming'
      url 'http://reddit.com/r/programming'
      document "Swift will be open sourced! Pixel City - Procedurally generated city NES Graphics - Part 2 Modules won't make it in C++17 Making the Case for using F# with Tomas Petricek (with Seth Juarez at Channel 9) [Codeless Code] Case 194: Stray securefs: a better transparent encryption filesystem ArrayFire, the recently open-sourced GPU programming library with an easy-to-use API, is now at v3.0. Developing For iOS Just Got A Whole Lot Cheaper. Apple Combines Dev Programs Into New Program. Kha: a cross-platform, low-level multimedia SDK using Haxe Types: computation vs. interaction Amazon Announces AWS SDK for Go Developers Preview Coding bootcamps see huge enrollment increase in 2015; Ruby most popular language Lessons learned: engineering productivity Stacksmith - an open source, modern day HyperCard clone On Managing Developers Interviewing candidates (on Eric Lippert's blog) How to Program It: Solving Problems Functionally Using Haskell Coming this fall with Xcode 7, everyone can install and run their apps on their iOS devices for free Minimal OpenGL 3.3 Core Profile Demo Implementing a programming language in C (Part 2) Apple's Swift programming language is going open source Song lyrics expressed in code Xilinx SDSoC program FPGA in C/ C++ the MicroZed Chronicles takes a look Network programming hints 4 games, part 3a (server-side, store-process-and-forward architecture)"
    end

    trait :ask_reddit do
      name 'Ask Reddit'
      url 'http://reddit.com/r/ask_reddit'
      document "Reddit, what is the best \"Reddit, we did it!\" moment that you were a part of? Is there an app for OS X that changes backgrounds from a repository the same way a Chromecast does? I've searched and searched but cannot find this old PC Gamer cover Besides masturbating, what do you do in private that would be weird in public? How do calories from alcohol compare to calories from food? (Ie is an 800 calorie 6 pack really the same as an 800 calorie big Mac meal?) What are some SNL secret traditions for the cast that may or may have not have been around since the Belushi era of SNL? How does Superman know when to metaphorically \"draw the line\" on helping? In other words, when does he say, \"You don't need me to do this; fix it yourself\"? [Serious]Where is a good website to get actual projections of the climate change models charted against actual temperatures? Reddit, what are some of the best charities to donate to, in order to fight these world plights? It is time... Reddit what is the meaning of life?? What sort of things would get me on the NSA's 'List'? Is it wrong to be jealous of your SO's celebrity crush? How short is too short for a frenulum? Right to be forgotten and privacy and self. Where is the line between \"curvy\" and \"chunky?\" Is it illegal for the NSA to share economic data? Any problem with Facebook now? How do I become an Industrial Designer? Why are thousands of service men and women coming back with \"PTSD\" and let it ruin our lives when our four fathers just \"carry on\" What happened with Consumerist for its reach to spike at the end of January? Excuse me, Reddit. Do you think you could identify this tree for me? What phone numbers can you still remember by heart? How much would you weigh if you could hypothetically survive a visit to the very center of the earth?  New Wifi Modem/Router; who knows some fun/cool/\nawesome/hilarious things to customize or improve it? Hey ask_reddit, what is the real url for askreddit?"
    end
  end
end
