language: ruby
sudo: required
rvm:
- '2.2.2'
- ruby-head
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev libgsl0-dbg
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake bower:install
  - cp config/database.yml.ig config/database.yml
  - cp config/secrets.yml.ig config/secrets.yml
  - bin/rake db:migrate RAILS_ENV=test
  - bundle exec rspec -fd
matrix:
  allow_failures:
  - rvm: ruby-head
