language: ruby
sudo: true
rvm:
- '2.2'
- ruby-head
before script:
  - echo apt-get install -qq --install-suggests install libgsl0-dev libgsl0-dbg
script:
  - bundle exec rspec -fd
matrix:
  allow_failures:
  - rvm: ruby-head
