language: ruby
sudo: required
rvm:
- '2.2'
- ruby-head
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev libgsl0-dbg
script:
  - bundle exec rspec -fd
matrix:
  allow_failures:
  - rvm: ruby-head
